apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: cicd-demo
        image: anjali511/cicd-demo 
        ports:
        - containerPort: 80
    